### ISSUE TITLE
Create AWS template CI pipeline

### ISSUE THREAD

**Issue by robe070** [robe070/cookbooks#81]
Implement similar functionality to the Azure template CI pipeline

**Comment by robe070** [comment]
Note that the base image id for AWS is `w12r2d-14-2` (Azure was `lansa-scalable-license-14-2`). All other base Image Ids are the same on AWS as for Azure. This effects the AWS Image and AWS template CI and CD pipeline parameters too.

**Comment by srinivasp898** [comment]
@robe070 
Below two URL are working fine after CFN template deployment

URL1: http://test-stac-webserve-1ofb3qzb8su06-356551863.ap-southeast-2.elb.amazonaws.com/cgi-bin/probe
URL2: http://test-stac-webserve-1ofb3qzb8su06-356551863.ap-southeast-2.elb.amazonaws.com/cgi-bin/lansaweb?about

And Below two URL are not working after CFN template deployment. Getting the error "Unrecoverable error occurred while executing the Web application routine"

$url3 = http://test-stac-webserve-1ofb3qzb8su06-356551863.ap-southeast-2.elb.amazonaws.com/cgi-bin/lansaweb?wam=DEPTABWA&webrtn=BuildFirst&ml=LANSA:XHTML&part=DEX&lang=ENG
$url4 = http://test-stac-webserve-1ofb3qzb8su06-356551863.ap-southeast-2.elb.amazonaws.com/cgi-bin/lansaweb?wam=JSMLICE&webrtn=weblic&ml=LANSA:XHTML&part=DEX&lang=ENG

**Comment by robe070** [comment]
I have addressed it here: https://github.com/robe070/cookbooks/issues/78#issuecomment-737514639

**Comment by srinivasp898** [comment]
@robe070 
I am trying to run below script in Pipeline. But it was throwing an error,please find the error in below screenshot.

***Script that am using***
Send-SSMCommand -DocumentName "AWS-RunRemoteScript" -Parameter @{ sourceType="GitHub";sourceInfo='{"owner": "robe070","repository": "cookbooks","branch": "debug/pass","path": "Tests/TestImageVersion.ps1"}'; "commandLine"="TestImageVersion.ps1"} -InstanceId i-0a3d611527057072f

And I checked in AWS console as below error git url is not formed correctly, even I pass correct parameters also.

![image](https://user-images.githubusercontent.com/73096247/100989225-9ceb2000-3576-11eb-9d5a-d7f682d53410.png)


***Pipeline OutPut***
Error : Status Pending 
[Link](url)

**Comment by robe070** [comment]
The link provided above does not work. I needed to hunt around for the run that did not work.
Here it is:
[AWS Console link](https://ap-southeast-2.console.aws.amazon.com/systems-manager/run-command/630d353f-f398-4398-bdf2-a16160b6af55?region=ap-southeast-2)
![image](https://user-images.githubusercontent.com/4089160/101099700-48e54780-3619-11eb-87d5-1939ef2bddf5.png)

And a working one:
![image](https://user-images.githubusercontent.com/4089160/101099858-a8dbee00-3619-11eb-806e-19789b3cba6c.png)

So maybe you've worked out how to do it? If so, would have been good to post that in here.

**Comment by srinivasp898** [comment]
@robe070 
below is the  working script, but in pipeline we are still getting status as pending

"$result = Send-SSMCommand -DocumentName "AWS-RunPowerShellScript" -InstanceId "$instanceId" -Parameter @{commands = ' New-Item -Path "$(CookbooksSource1)\Tests" -ItemType Directory -force -verbose; New-Item -Path "$(CookbooksSource1)\scripts" -ItemType Directory -force -verbose; Invoke-WebRequest -Uri "https://raw.githubusercontent.com/robe070/cookbooks/debug/paas/Tests/TestImageVersion.ps1" -OutFile "$(CookbooksSource1)\Tests\TestImageVersion.ps1" -verbose; Invoke-WebRequest -Uri "https://raw.githubusercontent.com/robe070/cookbooks/debug/paas/scripts/dot-CommonTools.ps1" -OutFile "$(CookbooksSource1)\scripts\dot-CommonTools.ps1" -verbose; . "$(CookbooksSource1)\scripts\dot-CommonTools.ps1"; $(CookbooksSource1)\Tests\TestImageVersion.ps1 -ImgName "$Skuname"'}"

![image](https://user-images.githubusercontent.com/73096247/101137321-aaff7600-3634-11eb-8d35-a807429e63da.png)

**Comment by robe070** [comment]
This won't resolve your issue, and I don't know what the resolution is, you will need to debug it.

You are explicitly using the branch `debug/paas` that needs to be a variable.

**Comment by robe070** [comment]
You may need to search for a resolution on the Internet.

**Comment by srinivasp898** [comment]
we updated branch as pipeline variable as below

-Uri "https://raw.githubusercontent.com/robe070/cookbooks/$(CookbooksBranch)/Tests/TestImageVersion.ps1" -OutFile "$(CookbooksSource1)\Tests\TestImageVersion.ps1" -verbose; Invoke-WebRequest -Uri "https://raw.githubusercontent.com/robe070/cookbooks/$(CookbooksBranch)/scripts/dot-CommonTools.ps1"

**Comment by srinivasp898** [comment]
> This won't resolve your issue, and I don't know what the resolution is, you will need to debug it.
> 
> You are explicitly using the branch `debug/paas` that needs to be a variable.

Now we are getting status success. PFA of below screen shot.
![image](https://user-images.githubusercontent.com/73096247/101245281-bedcd200-3731-11eb-9af7-e932cb7b3ad8.png)

**Comment by srinivasp898** [comment]
> @robe070
> below is the working script, but in pipeline we are still getting status as pending
> 
> "$result = Send-SSMCommand -DocumentName "AWS-RunPowerShellScript" -InstanceId "$instanceId" -Parameter @{commands = ' New-Item -Path "$(CookbooksSource1)\Tests" -ItemType Directory -force -verbose; New-Item -Path "$(CookbooksSource1)\scripts" -ItemType Directory -force -verbose; Invoke-WebRequest -Uri "https://raw.githubusercontent.com/robe070/cookbooks/debug/paas/Tests/TestImageVersion.ps1" -OutFile "$(CookbooksSource1)\Tests\TestImageVersion.ps1" -verbose; Invoke-WebRequest -Uri "https://raw.githubusercontent.com/robe070/cookbooks/debug/paas/scripts/dot-CommonTools.ps1" -OutFile "$(CookbooksSource1)\scripts\dot-CommonTools.ps1" -verbose; . "$(CookbooksSource1)\scripts\dot-CommonTools.ps1"; $(CookbooksSource1)\Tests\TestImageVersion.ps1 -ImgName "$Skuname"'}"
> 
> ![image](https://user-images.githubusercontent.com/73096247/101137321-aaff7600-3634-11eb-8d35-a807429e63da.png)

Successfully tested all URL(s). with new(lansa-master-win.cfn.template) template.

**Comment by robe070** [comment]
so what is the difference between the pipeline that had status `success` and the pipeline that is left `pending`?
Where is the code in the pipeline?

**Comment by srinivasp898** [comment]
I updated while condition as below, it will wait until success
```
"while ($result.Status -eq "Pending" -or $result.Status -eq "InProgress"){
    $result = Get-SSMCommand -InstanceId $result.InstanceId -CommandId $result.CommandId}"

```

**Comment by robe070** [comment]
So is there actually still an issue for me to resolve?

**Comment by srinivasp898** [comment]
> So is there actually still an issue for me to resolve?

No We are good  ,

need help on taskcat validation still getting permission denied error
[https://iderainc.slack.com/archives/C01D4NFR4RJ/p1606375654195500?thread_ts=1606364558.188900&cid=C01D4NFR4RJ](url)

**Comment by srinivasp898** [comment]
we updated tags for cfn templates from pipeline

and created folder in s3 bucket to upload templates (lansa/templates/debug/paas/pipeline) is this ok or any changes required

[https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/stackinfo?filteringText=&filteringStatus=active&viewNested=true&hideStacks=true&stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2Ftest-stack-pipe%2F31024c90-3960-11eb-826d-02136ea02430](url)

**Comment by robe070** [comment]
Interesting that you have posted this. I reviewed the AWS Template Release pipeline about an hour ago and realised that we have a clash with template upload location.

The fundamental architecture is that the cookbooks branch is the folder name in S3. So `debug/paas/pipeline` does not fit unless you create a branch with that name in the cookbooks repo.

I need to resolve this with AWS marketplace as it goes further than just the pipeline, its how we develop and promote the templates from coding all the way through the pipeline to final release to the public. Maybe AWS host the templates in their own S3 buckets. I need to check this out, but then how do the nested templates work?

**Comment by srinivasp898** [comment]
Raised PR ,please review and let us know if there is any changes.

**Comment by srinivasp898** [comment]
1.Removed print deployment output task
2.Given imageid as skunameold , need to update  manually once ami id is updated. 
is there anything need to update or we can merge/close this task

**Comment by srinivasp898** [comment]
We are using support/scalable branch in lansa/aws-templates,
Updated correct SKU name  in test image version script in CI pipeline.

**Comment by robe070** [comment]
I'm waiting for a successful build before closing this issue. Please inform me when that has occurred.

**Comment by srinivasp898** [comment]
Hi @robe070, 
Build completed successful after adding the VPC parameters and Cleanup CFN Template before the deploying stack. 
Please find the screen shot below.  Build Number#774

![image](https://user-images.githubusercontent.com/73096247/102350601-295ffe80-3fcb-11eb-98cb-23b2e7c80a51.png)

**Comment by srinivasp898** [comment]
Hi @Robert Goodridge I updated cleanup stack with aws powershell which will delete stack if exist in CI pipeline , please let me if any changes required
![image](https://user-images.githubusercontent.com/73096247/102387019-e1a29c80-3ff5-11eb-94f8-a0d81b308305.png)

**Comment by robe070** [comment]
You need to use the cookbooks git repo branch name in the template location AND specify it when launching the template - `10LansaGitRepoBranch`.
Do NOT use a literal. Create a variable to be used in BOTH places. Call the variable `CookbooksBranch`. This is the same variable name that Image Release CD pipeline uses.

**Comment by srinivasp898** [comment]
Added archive file task for CI pipeline
and updated variable in parameter's for deploy cfn template task, please let me know if any changes required

**Comment by robe070** [comment]
> You need to use the cookbooks git repo branch name in the template location AND specify it when launching the template - `10LansaGitRepoBranch`.
> Do NOT use a literal. Create a variable to be used in BOTH places. Call the variable `CookbooksBranch`. This is the same variable name that Image Release CD pipeline uses.

It doesn't look like you've done the above, which needs to be done.

Which begs the question, what variable's precisely did you change from what to what?

**Comment by srinivasp898** [comment]
i used above parameter in deploy cfn template task parameter's as below for CookbooksBranch
![image](https://user-images.githubusercontent.com/73096247/102456497-3f230180-4067-11eb-93e5-80ef87ec1602.png)

**Comment by robe070** [comment]
Ditto CD pipeline comment.

**Comment by srinivasp898** [comment]
updated in s3 bucket task parameter as below in ci pipeline. please let me know if any changes required
![image](https://user-images.githubusercontent.com/73096247/102464019-d68d5200-4071-11eb-8ecf-7f7e4e1c1121.png)

**Comment by robe070** [comment]
Seriously? Check your work. Double check you’ve not got a reference
somewhere to a branch!!!!!!!!!!!!!!



I’m not your desk checker. Do it yourself! Here is just 1 example!!!!!!!!





Warm regards



*Rob Goodridge *| CloudArchitect | *LANSA Product Centre*



*From:* srinivasp898 <notifications@github.com>
*Sent:* Thu, 17 December 2020 7:43 PM
*To:* robe070/cookbooks <cookbooks@noreply.github.com>
*Cc:* Rob Goodridge <robert.goodridge@lansa.com.au>; Mention <
mention@noreply.github.com>
*Subject:* Re: [robe070/cookbooks] Create AWS template CI pipeline (#81)



updated in s3 bucket task parameter as below in ci pipeline. please let me
know if any changes required
[image: image]
<https://user-images.githubusercontent.com/73096247/102464019-d68d5200-4071-11eb-8ecf-7f7e4e1c1121.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/robe070/cookbooks/issues/81#issuecomment-747297573>, or
unsubscribe

**Comment by srinivasp898** [comment]
Hi Rob , ci pipeline is reviewed by Varun  he said everything ok after updating  variable CookbooksBranch , can we close this task if everything working fine.
